### ISSUE TITLE
 How does the server  send invite to the client

### ISSUE THREAD

**Issue by xiaoxiaodetian** [ghettovoice/gosip#10]
How does the server send invite to the client after register

**Comment by ghettovoice** [comment]
Hello @xiaoxiaodetian ,
you should build and send invite request by yourself.
For example like this:

```go
ctx := context.Background()
body := "sdp offer"
contentType := sip.ContentType("application/sdp")
callIDHeader := sip.CallID(callID)
// build request using sip.RequestBuilder
// or with sip.NewRequest contructor
rb := sip.NewRequestBuilder().
		SetHost("example.com").
		SetMethod(sip.INVITE).
		SetRecipient("bob@example.com").
		AddVia(&sip.ViaHop{
			Params: sip.NewParams().Add("branch", sip.NewString(sip.GenerateBranch())),
		}).
		SetTo("bob@example.com").
		SetFrom("alice@example.com").
		SetContact("bob@example.com").
		SetContentType(&contentType).
		SetCallID(&callIDHeader).
		SetBody(body + "\r\n")
	inviteRequest, err := rb.Build()
	if err != nil {
		panic(fmt.Errorf("build INVITE request: %w", err))
	}

	response, err := ua.RequestWithContext(ctx, inviteRequest)
	if err != nil {
		panic(fmt.Errorf("execute INVITE request: %w", err))
	}
```

**Comment by 0x5e** [comment]
I'm sending an incorrect INVITE message and got an 404 Bad Request, then an infinite "ACK - 404 - ACK - 404 - ..." loop. The ACK message is not fired by me. Are there any params to disable it?

Tried `srv.RequestWithContext` and `srv.Request`, same issue.
<img width="1624" alt="image" src="https://github.com/ghettovoice/gosip/assets/5144674/6f33f5ac-fc4e-42f2-98f2-834ad003f2f8">

**Comment by ghettovoice** [comment]
Hello @0x5e ,
ACK on failure final response is generated and sent by the client transaction. After final response with status >= 3xx
the client transaction stays in completed state until expired after 32s. During this time it resends last ACK on each response retransmit.
The target UA at 192.168.60.141 is working incorrect, because it resends 400 response on ACK. ACK request doesn't require any response, It only needs to complete server tx on remote side. But anyway, after ~32s your client INVITE transaction will be terminated and stop resend ACK.

**Comment by 0x5e** [comment]
@ghettovoice got it, thanks for the detail explain!
